import { RegionSpotConfig } from "@/types/region";

/**
 * Alta Toscana Edition MVP Spot Configurations (Versilia, Pisan Coast, Etruscan Coast)
 */
export const AltaToscanaSpots: RegionSpotConfig[] = [
  {
    id: "calambrone",
    name: "Calambrone",
    latitude: 43.593,
    longitude: 10.298,
    description: "Pisan Coast / Calambrone • Regional freeride reference spot with high wind frequency and active summer thermal acceleration.",
    sweetSpotSummary: "Optimal in 16–26 kt W/SW/NW flows; strong thermal reinforcement in summer afternoons.",
    idealDirections: ["W", "WSW", "SW", "NW", "WNW"],
    idealDirectionDegrees: [210, 330],
    minPlaningWind: 11,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 30,
    defaultStyle: "FLAT",
    directionScores: {
      W: 100,
      WSW: 95,
      SW: 90,
      NW: 90,
      WNW: 85,
      SSW: 75,
      NNW: 70,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 26,
      bumpAndJumpThresholdWind: 20,
      favoredDirections: ["SW", "WSW", "W"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 10, score: 20 },
      { wind: 14, score: 60 },
      { wind: 18, score: 95 },
      { wind: 23, score: 100 },
      { wind: 27, score: 85 },
      { wind: 32, score: 55 },
      { wind: 40, score: 15 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.06,
      minFactor: 0.90,
      maxFactor: 1.35,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        enabled: true,
        maxBoost: 0.18,
        monthFactors: {
          5: 0.6,
          6: 0.9,
          7: 1.0,
          8: 1.0,
          9: 0.7,
        },
        timeProfile: [
          { hour: 11, factor: 0.10 },
          { hour: 12, factor: 0.35 },
          { hour: 13, factor: 0.60 },
          { hour: 14, factor: 0.85 },
          { hour: 15, factor: 1.00 },
          { hour: 16, factor: 0.95 },
          { hour: 17, factor: 0.75 },
          { hour: 18, factor: 0.40 },
          { hour: 19, factor: 0.10 },
        ],
        directionFactors: {
          W: 1.00,
          WSW: 1.00,
          WNW: 0.95,
          SW: 0.85,
          NW: 0.80,
        },
        defaultDirectionFactor: 0.10,
        synopticWindCurve: [
          { wind: 0, factor: 0.20 },
          { wind: 4, factor: 0.70 },
          { wind: 8, factor: 1.00 },
          { wind: 12, factor: 1.00 },
          { wind: 16, factor: 0.75 },
          { wind: 20, factor: 0.35 },
          { wind: 24, factor: 0.00 },
        ],
        cloudCoverCurve: [
          { cloud: 0, factor: 1.00 },
          { cloud: 20, factor: 1.00 },
          { cloud: 40, factor: 0.90 },
          { cloud: 60, factor: 0.60 },
          { cloud: 80, factor: 0.25 },
          { cloud: 100, factor: 0.05 },
        ],
        minThermalStrength: 0.05,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "W", factor: 0.85 },
        { direction: "WSW", factor: 0.85 },
        { direction: "SW", factor: 0.80 },
        { direction: "WNW", factor: 0.80 },
        { direction: "NW", factor: 0.75 },
      ],
      preferredWaveHeight: {
        min: 0.2,
        idealMin: 0.4,
        idealMax: 1.2,
        max: 2.0,
      },
      preferredPeriod: {
        min: 4.0,
        idealMin: 5.0,
        idealMax: 8.5,
      },
      preferredStates: {
        FLAT: 1.0,
        CHOP: 0.85,
        BUMP_AND_JUMP: 0.6,
        WAVE: 0.2,
      },
    },
    hardGates: [
      {
        id: "calambrone-offshore-east",
        description: "Offshore flow from inland Pisa / Livorno plain (NE/E/ENE)",
        directionRange: [45, 120],
        eligibility: "UNSUITABLE",
        reason: "Offshore wind from the pine forest creates dangerous drift and severe gustiness.",
      },
    ],
  },
  {
    id: "vada",
    name: "Vada",
    latitude: 43.355,
    longitude: 10.448,
    description: "Spiagge Bianche • High-performance freeride and bump & jump arena with prominent Maestrale (NW) acceleration.",
    sweetSpotSummary: "Optimal in 18–28 kt NW/WNW/W flow; strong Venturi & coastal boost.",
    idealDirections: ["NW", "WNW", "W", "NNW", "SW"],
    idealDirectionDegrees: [225, 345],
    minPlaningWind: 12,
    idealWindMin: 18,
    idealWindMax: 28,
    comfortCeilingWind: 32,
    defaultStyle: "BUMP_AND_JUMP",
    directionScores: {
      NW: 100,
      WNW: 95,
      W: 90,
      NNW: 85,
      SW: 80,
      SSW: 70,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["NW", "WNW", "W"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 15, score: 55 },
      { wind: 20, score: 95 },
      { wind: 25, score: 100 },
      { wind: 30, score: 85 },
      { wind: 36, score: 50 },
      { wind: 42, score: 15 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.12,
      minFactor: 0.90,
      maxFactor: 1.35,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.06,
      directionModifiers: {
        NW: 0.12,
        WNW: 0.08,
        W: 0.05,
        NNW: 0.05,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "NW", factor: 0.95 },
        { direction: "WNW", factor: 0.90 },
        { direction: "W", factor: 0.85 },
        { direction: "WSW", factor: 0.85 },
        { direction: "SW", factor: 0.80 },
      ],
      preferredWaveHeight: {
        min: 0.5,
        idealMin: 0.9,
        idealMax: 2.0,
        max: 3.0,
      },
      preferredPeriod: {
        min: 4.5,
        idealMin: 6.0,
        idealMax: 9.5,
      },
      preferredWaveDirections: ["NW", "WNW", "W"],
      preferredStates: {
        BUMP_AND_JUMP: 1.0,
        WAVE: 0.8,
        CHOP: 0.6,
        FLAT: 0.5,
      },
    },
    hardGates: [
      {
        id: "vada-offshore-east",
        description: "Offshore wind from the Tuscan hills (ENE/E/ESE)",
        directionRange: [60, 120],
        eligibility: "UNSUITABLE",
        reason: "Offshore flow creates hazardous seaward drift away from the white beaches.",
      },
    ],
  },
  {
    id: "il-sale",
    name: "Il Sale",
    latitude: 43.518,
    longitude: 10.315,
    description: "Livorno / Antignano • Legendary rocky reef wave arena exposed to powerful W/SW swell for experienced wave riders.",
    sweetSpotSummary: "Optimal in 20–35 kt SW Libeccio / W Ponente with organized wave swell.",
    idealDirections: ["SW", "WSW", "SSW", "W", "WNW"],
    idealDirectionDegrees: [200, 300],
    minPlaningWind: 14,
    idealWindMin: 18,
    idealWindMax: 32,
    comfortCeilingWind: 38,
    defaultStyle: "WAVE",
    preferredStyles: {
      WAVE: 1.0,
      BUMP_AND_JUMP: 0.6,
      CHOP: 0.2,
      FLAT: 0.0,
    },
    directionScores: {
      SW: 100,
      WSW: 95,
      W: 95,
      SSW: 90,
      WNW: 80,
      default: 25,
    },
    styleRules: {
      waveThresholdWind: 18,
      bumpAndJumpThresholdWind: 15,
      favoredDirections: ["SW", "WSW", "W", "SSW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 12, score: 10 },
      { wind: 16, score: 45 },
      { wind: 20, score: 85 },
      { wind: 25, score: 100 },
      { wind: 30, score: 100 },
      { wind: 35, score: 90 },
      { wind: 42, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.08,
      minFactor: 0.90,
      maxFactor: 1.30,
      directionModifiers: {
        SW: 0.08,
        WSW: 0.06,
        W: 0.05,
        SSW: 0.05,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "SW", factor: 1.00 },
        { direction: "WSW", factor: 1.00 },
        { direction: "W", factor: 0.95 },
        { direction: "SSW", factor: 0.90 },
        { direction: "WNW", factor: 0.85 },
      ],
      heightQualityCurve: [
        { height: 0.3, score: 10 },
        { height: 0.8, score: 45 },
        { height: 1.4, score: 85 },
        { height: 2.0, score: 100 },
        { height: 2.8, score: 90 },
        { height: 3.8, score: 50 },
      ],
      preferredPeriod: {
        min: 6.0,
        idealMin: 7.5,
        idealMax: 12.0,
      },
      preferredWaveDirections: ["SW", "WSW", "W"],
      preferredStates: {
        WAVE: 1.0,
        BUMP_AND_JUMP: 0.6,
        CHOP: 0.2,
        FLAT: 0.0,
      },
    },
    hardGates: [
      {
        id: "il-sale-offshore-east",
        description: "Offshore wind from the Livorno cliffs (NE/E/SE)",
        directionRange: [45, 135],
        eligibility: "UNSUITABLE",
        reason: "Offshore wind off the rocky cliffs creates severe wind shadows and dangerous rocky drift.",
      },
      {
        id: "il-sale-extreme-wave",
        description: "Hazardous wave height exceeding safe rocky reef entrance",
        minWaveHeight: 4.2,
        eligibility: "UNSUITABLE",
        reason: "Extreme swell (>4.2m) creates dangerous breaking conditions over the shallow rocky reef.",
      },
    ],
  },
  {
    id: "lido-di-camaiore",
    name: "Lido di Camaiore",
    latitude: 43.903,
    longitude: 10.218,
    description: "Central Versilia • Classic sandy beach break delivering organized SW swell and side-onshore wave riding.",
    sweetSpotSummary: "Optimal in 18–30 kt SW/WSW Libeccio and Ponente with clean wave ramps.",
    idealDirections: ["SW", "WSW", "W", "SSW", "WNW"],
    idealDirectionDegrees: [210, 310],
    minPlaningWind: 12,
    idealWindMin: 18,
    idealWindMax: 28,
    comfortCeilingWind: 32,
    defaultStyle: "WAVE",
    preferredStyles: {
      WAVE: 1.0,
      BUMP_AND_JUMP: 0.8,
      CHOP: 0.4,
      FLAT: 0.2,
    },
    directionScores: {
      SW: 100,
      WSW: 95,
      W: 90,
      SSW: 85,
      WNW: 80,
      NW: 70,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 20,
      bumpAndJumpThresholdWind: 16,
      favoredDirections: ["SW", "WSW", "W"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 16, score: 50 },
      { wind: 21, score: 90 },
      { wind: 26, score: 100 },
      { wind: 31, score: 80 },
      { wind: 37, score: 40 },
      { wind: 44, score: 10 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.04,
      minFactor: 0.90,
      maxFactor: 1.25,
      directionModifiers: {
        SW: 0.06,
        WSW: 0.05,
        W: 0.04,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "SW", factor: 0.95 },
        { direction: "WSW", factor: 0.95 },
        { direction: "W", factor: 0.90 },
        { direction: "SSW", factor: 0.85 },
        { direction: "WNW", factor: 0.80 },
      ],
      preferredWaveHeight: {
        min: 0.7,
        idealMin: 1.1,
        idealMax: 2.2,
        max: 3.2,
      },
      preferredPeriod: {
        min: 5.5,
        idealMin: 7.0,
        idealMax: 10.5,
      },
      preferredWaveDirections: ["SW", "WSW", "W"],
      preferredStates: {
        WAVE: 1.0,
        BUMP_AND_JUMP: 0.8,
        CHOP: 0.4,
        FLAT: 0.2,
      },
    },
    hardGates: [
      {
        id: "lido-camaiore-offshore",
        description: "Direct offshore wind from the Apuan Alps (ENE/E/ESE)",
        directionRange: [45, 135],
        eligibility: "UNSUITABLE",
        reason: "Offshore wind from the Apuan Alps creates hazardous seaward drift and turbulence.",
      },
    ],
  },
  {
    id: "forte-dei-marmi",
    name: "Forte dei Marmi",
    latitude: 43.958,
    longitude: 10.165,
    description: "Northern Versilia • Pier influence wave spot reacting to SW Libeccio and direct Ponente swell.",
    sweetSpotSummary: "Optimal in 18–30 kt SW/W flow with rolling surf lines.",
    idealDirections: ["SW", "WSW", "W", "SSW"],
    idealDirectionDegrees: [210, 295],
    minPlaningWind: 13,
    idealWindMin: 18,
    idealWindMax: 30,
    comfortCeilingWind: 34,
    defaultStyle: "WAVE",
    directionScores: {
      SW: 100,
      WSW: 95,
      W: 90,
      SSW: 85,
      WNW: 75,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 20,
      bumpAndJumpThresholdWind: 16,
      favoredDirections: ["SW", "WSW", "W"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 16, score: 50 },
      { wind: 21, score: 90 },
      { wind: 26, score: 100 },
      { wind: 31, score: 85 },
      { wind: 37, score: 50 },
      { wind: 44, score: 20 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.04,
      minFactor: 0.90,
      maxFactor: 1.25,
      directionModifiers: {
        SW: 0.06,
        WSW: 0.05,
        W: 0.04,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "SW", factor: 0.95 },
        { direction: "WSW", factor: 0.90 },
        { direction: "W", factor: 0.90 },
        { direction: "SSW", factor: 0.80 },
        { direction: "WNW", factor: 0.80 },
      ],
      preferredWaveHeight: {
        min: 0.6,
        idealMin: 1.0,
        idealMax: 2.2,
        max: 3.0,
      },
      preferredPeriod: {
        min: 5.5,
        idealMin: 7.0,
        idealMax: 10.5,
      },
      preferredWaveDirections: ["SW", "WSW", "W"],
      preferredStates: {
        WAVE: 1.0,
        BUMP_AND_JUMP: 0.8,
        CHOP: 0.4,
        FLAT: 0.2,
      },
    },
    hardGates: [
      {
        id: "forte-marmi-offshore",
        description: "Direct offshore wind from the Apuan Alps (NE/E/SE)",
        directionRange: [45, 135],
        eligibility: "UNSUITABLE",
        reason: "Offshore wind from the Apuan Alps creates hazardous seaward drift and gusty offshore conditions.",
      },
    ],
  },
  {
    id: "castagneto-donoratico",
    name: "Donoratico",
    latitude: 43.185,
    longitude: 10.538,
    description: "Marina di Castagneto Donoratico • Versatile freeride and bump & jump beach break transitioning to Maremma.",
    sweetSpotSummary: "Optimal in 16–26 kt S/SSW/SW/NW flow with rolling chop.",
    idealDirections: ["SW", "SSW", "W", "NW", "S"],
    idealDirectionDegrees: [180, 320],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 30,
    defaultStyle: "BUMP_AND_JUMP",
    directionScores: {
      SW: 95,
      SSW: 90,
      W: 90,
      NW: 85,
      S: 80,
      WNW: 80,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["SW", "SSW", "W", "NW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 15, score: 55 },
      { wind: 20, score: 95 },
      { wind: 24, score: 100 },
      { wind: 28, score: 80 },
      { wind: 34, score: 50 },
      { wind: 40, score: 20 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.05,
      minFactor: 0.90,
      maxFactor: 1.30,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.06,
      directionModifiers: {
        SW: 0.05,
        SSW: 0.05,
        W: 0.04,
        NW: 0.04,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "SW", factor: 0.90 },
        { direction: "SSW", factor: 0.85 },
        { direction: "W", factor: 0.85 },
        { direction: "WSW", factor: 0.85 },
        { direction: "NW", factor: 0.75 },
      ],
      preferredWaveHeight: {
        min: 0.3,
        idealMin: 0.6,
        idealMax: 1.5,
        max: 2.4,
      },
      preferredPeriod: {
        min: 4.5,
        idealMin: 6.0,
        idealMax: 9.0,
      },
      preferredWaveDirections: ["SW", "SSW", "W"],
      preferredStates: {
        BUMP_AND_JUMP: 1.0,
        CHOP: 0.9,
        FLAT: 0.8,
        WAVE: 0.6,
      },
    },
    hardGates: [
      {
        id: "donoratico-offshore-east",
        description: "Offshore wind from the inland hills (ENE/E/ESE)",
        directionRange: [60, 120],
        eligibility: "UNSUITABLE",
        reason: "Offshore wind creates hazardous seaward drift.",
      },
    ],
  },
];
