import { RegionSpotConfig } from "@/types/region";

/**
 * Lake Como Edition Initial Spot Configurations
 * Supports Tivano, Breva, Valmadrera post-rain acceleration, and Dervio strong North / Föhn.
 */
export const ComoLakeSpots: RegionSpotConfig[] = [
  {
    id: "valmadrera-pare",
    name: "Valmadrera–Parè",
    latitude: 45.845,
    longitude: 9.380,
    description: "Lecco Branch / Parè • Renowned early morning Tivano and post-rain northerly drainage arena.",
    sweetSpotSummary: "Optimal in 17–25 kt N/NNE/NE morning Tivano (05:30–10:30) with flat to small chop water.",
    idealDirections: ["N", "NNE", "NE", "ENE"],
    idealDirectionDegrees: [0, 80],
    minPlaningWind: 13,
    idealWindMin: 17,
    idealWindMax: 25,
    comfortCeilingWind: 29,
    defaultStyle: "FLAT",
    directionScores: {
      N: 100,
      NNE: 100,
      NE: 95,
      ENE: 85,
      NNW: 75,
      default: 20,
    },
    styleRules: {
      bumpAndJumpThresholdWind: 22,
      favoredDirections: ["N", "NNE", "NE"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 20 },
      { wind: 14, score: 70 },
      { wind: 18, score: 95 },
      { wind: 23, score: 100 },
      { wind: 28, score: 80 },
      { wind: 34, score: 40 },
    ],
    operatingWindow: {
      mode: "SOLAR_WITH_TWILIGHT",
      preSunriseMinutes: 45,
      earliestLocalTime: "05:15",
      latestLocalTime: "12:00",
    },
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.90,
      maxFactor: 1.40,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        enabled: true,
        maxBoost: 0.22,
        monthFactors: {
          4: 0.7,
          5: 0.9,
          6: 1.0,
          7: 1.0,
          8: 1.0,
          9: 0.9,
          10: 0.7,
        },
        timeProfile: [
          { hour: 5.0, factor: 0.30 },
          { hour: 6.0, factor: 0.75 },
          { hour: 7.0, factor: 1.00 },
          { hour: 8.0, factor: 1.00 },
          { hour: 9.0, factor: 0.85 },
          { hour: 10.0, factor: 0.55 },
          { hour: 11.0, factor: 0.20 },
          { hour: 12.0, factor: 0.00 },
        ],
        directionFactors: {
          N: 1.00,
          NNE: 1.00,
          NE: 0.95,
          ENE: 0.80,
          NNW: 0.70,
        },
        defaultDirectionFactor: 0.10,
        synopticWindCurve: [
          { wind: 0, factor: 0.30 },
          { wind: 4, factor: 0.80 },
          { wind: 8, factor: 1.00 },
          { wind: 14, factor: 1.00 },
          { wind: 18, factor: 0.60 },
          { wind: 24, factor: 0.00 },
        ],
        cloudCoverCurve: [
          { cloud: 0, factor: 1.00 },
          { cloud: 20, factor: 1.00 },
          { cloud: 40, factor: 0.85 },
          { cloud: 60, factor: 0.50 },
          { cloud: 80, factor: 0.20 },
          { cloud: 100, factor: 0.05 },
        ],
        minThermalStrength: 0.05,
      },
      conditionalBoosts: [
        {
          applicableRegimeIds: ["COMO_POST_RAIN_NORTH"],
          minRecentPrecipitation: 1.0,
          boostAmount: 0.20,
        },
      ],
    },
    lakeProfile: {
      fetchByDirectionKm: { N: 14, NNE: 16, NE: 10, ENE: 6, NNW: 8, S: 2 },
      flatThresholdKt: 14,
      chopThresholdKt: 20,
      rampThresholdKt: 28,
      extremeThresholdKt: 36,
    },
    hardGates: [
      {
        id: "valmadrera-southerly-shadow",
        description: "Obstructed southerly wind in the Lecco branch (S/SSW/SW)",
        directionRange: [150, 240],
        eligibility: "UNSUITABLE",
        reason: "Southerly airflow is heavily sheltered by Mount Barro and Lecco surrounding mountains.",
      },
      {
        id: "valmadrera-convective-hazard",
        description: "Active convective hazard or thunderstorm",
        regimes: ["COMO_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Dangerous thunderstorm outflow and lightning near the lake.",
      },
    ],
  },
  {
    id: "dervio",
    name: "Dervio",
    latitude: 46.075,
    longitude: 9.305,
    description: "Central Lake Como • High-performance Breva thermal hub and premier strong North / Föhn windsurfing arena.",
    sweetSpotSummary: "Optimal in 16–28 kt S/SSW Breva afternoons or 22–35 kt strong North / Föhn events.",
    idealDirections: ["S", "SSW", "SSE", "N", "NNW"],
    idealDirectionDegrees: [160, 360],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 30,
    comfortCeilingWind: 36,
    defaultStyle: "CHOP",
    preferredStyles: {
      CHOP: 1.0,
      BUMP_AND_JUMP: 0.9,
      FLAT: 0.8,
    },
    directionScores: {
      S: 100,
      SSW: 100,
      SSE: 95,
      N: 100,
      NNW: 95,
      default: 25,
    },
    styleRules: {
      waveThresholdWind: 26,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["S", "SSW", "N", "NNW"],
    },
    regimeQualityCurves: {
      COMO_STRONG_NORTH: [
        { wind: 0, score: 0 },
        { wind: 14, score: 30 },
        { wind: 18, score: 75 },
        { wind: 24, score: 100 },
        { wind: 30, score: 98 },
        { wind: 35, score: 80 },
        { wind: 42, score: 35 },
      ],
      COMO_FOEHN: [
        { wind: 0, score: 0 },
        { wind: 16, score: 35 },
        { wind: 22, score: 80 },
        { wind: 28, score: 100 },
        { wind: 34, score: 85 },
        { wind: 40, score: 50 },
        { wind: 46, score: 20 },
      ],
      COMO_BREVA: [
        { wind: 0, score: 0 },
        { wind: 11, score: 20 },
        { wind: 15, score: 65 },
        { wind: 18, score: 95 },
        { wind: 24, score: 100 },
        { wind: 28, score: 85 },
        { wind: 34, score: 40 },
      ],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 20 },
      { wind: 15, score: 65 },
      { wind: 18, score: 95 },
      { wind: 24, score: 100 },
      { wind: 30, score: 95 },
      { wind: 36, score: 75 },
      { wind: 45, score: 30 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.12,
      minFactor: 0.90,
      maxFactor: 1.35,
      directionModifiers: {
        S: 0.10,
        SSW: 0.08,
        N: 0.10,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: { S: 18, SSW: 22, SSE: 12, N: 16, NNW: 18 },
      flatThresholdKt: 12,
      chopThresholdKt: 16,
      rampThresholdKt: 24,
      extremeThresholdKt: 35,
    },
    hardGates: [
      {
        id: "dervio-convective-hazard",
        description: "Active convective hazard or thunderstorm",
        regimes: ["COMO_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Dangerous thunderstorm outflow and lightning over the central lake basin.",
      },
      {
        id: "dervio-offshore-east",
        description: "Offshore wind from the Valsassina mountains (ENE/E/ESE)",
        directionRange: [60, 120],
        eligibility: "UNSUITABLE",
        reason: "Offshore mountain wind creates turbulent gusts and dangerous seaward drift.",
      },
    ],
  },
  {
    id: "colico",
    name: "Colico",
    latitude: 46.135,
    longitude: 9.365,
    description: "Northern Lake / Montecchio • Broad bay catching reinforced afternoon Breva with wide launch.",
    sweetSpotSummary: "Optimal in 16–26 kt S/SSW Breva with rolling lake chop and safe recovery.",
    idealDirections: ["S", "SSW", "SW", "N", "NNW"],
    idealDirectionDegrees: [170, 350],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 32,
    defaultStyle: "CHOP",
    directionScores: {
      S: 100,
      SSW: 95,
      SW: 85,
      N: 80,
      default: 25,
    },
    styleRules: {
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["S", "SSW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 15, score: 55 },
      { wind: 20, score: 95 },
      { wind: 25, score: 100 },
      { wind: 30, score: 80 },
      { wind: 36, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.90,
      maxFactor: 1.30,
      directionModifiers: {
        S: 0.08,
        SSW: 0.06,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: { S: 22, SSW: 24, SW: 14, N: 8 },
      flatThresholdKt: 12,
      chopThresholdKt: 16,
      rampThresholdKt: 25,
      extremeThresholdKt: 35,
    },
    hardGates: [
      {
        id: "colico-convective-hazard",
        description: "Active convective hazard",
        regimes: ["COMO_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Severe convective downburst conditions.",
      },
    ],
  },
  {
    id: "gera-lario",
    name: "Gera Lario",
    latitude: 46.168,
    longitude: 9.368,
    description: "Northernmost Lake Tip • Flat to chop freeride haven where afternoon Breva compresses against the Alps.",
    sweetSpotSummary: "Optimal in 15–25 kt S/SSW Breva with flat to small chop water.",
    idealDirections: ["S", "SSW", "SSE"],
    idealDirectionDegrees: [160, 220],
    minPlaningWind: 11,
    idealWindMin: 15,
    idealWindMax: 24,
    comfortCeilingWind: 28,
    defaultStyle: "FLAT",
    directionScores: {
      S: 100,
      SSW: 95,
      SSE: 85,
      default: 20,
    },
    styleRules: {
      bumpAndJumpThresholdWind: 20,
      favoredDirections: ["S", "SSW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 20 },
      { wind: 15, score: 65 },
      { wind: 19, score: 95 },
      { wind: 23, score: 100 },
      { wind: 27, score: 75 },
      { wind: 33, score: 30 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.08,
      minFactor: 0.90,
      maxFactor: 1.30,
      directionModifiers: {
        S: 0.06,
        SSW: 0.05,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: { S: 24, SSW: 26, SSE: 16, N: 4 },
      flatThresholdKt: 14,
      chopThresholdKt: 19,
      rampThresholdKt: 26,
      extremeThresholdKt: 35,
    },
    hardGates: [
      {
        id: "gera-convective-hazard",
        description: "Active convective hazard",
        regimes: ["COMO_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Thunderstorm activity near the alpine boundary.",
      },
    ],
  },
  {
    id: "cremia",
    name: "Cremia",
    latitude: 46.088,
    longitude: 9.278,
    description: "Western Shore / San Vito • Venturi channel acceleration delivering steady early Breva and moderate chop.",
    sweetSpotSummary: "Optimal in 16–26 kt S/SSW Breva; builds earlier than the upper lake due to lake narrowing.",
    idealDirections: ["S", "SSW", "SSE", "N"],
    idealDirectionDegrees: [160, 220],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 30,
    defaultStyle: "CHOP",
    directionScores: {
      S: 100,
      SSW: 95,
      SSE: 85,
      N: 75,
      default: 25,
    },
    styleRules: {
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["S", "SSW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 15, score: 60 },
      { wind: 20, score: 95 },
      { wind: 24, score: 100 },
      { wind: 29, score: 80 },
      { wind: 35, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.90,
      maxFactor: 1.35,
      directionModifiers: {
        S: 0.08,
        SSW: 0.06,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: { S: 16, SSW: 18, SSE: 10, N: 12 },
      flatThresholdKt: 12,
      chopThresholdKt: 16,
      rampThresholdKt: 24,
      extremeThresholdKt: 35,
    },
    hardGates: [
      {
        id: "cremia-convective-hazard",
        description: "Active convective hazard",
        regimes: ["COMO_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Severe convective downburst conditions.",
      },
    ],
  },
  {
    id: "gravedona",
    name: "Gravedona",
    latitude: 46.145,
    longitude: 9.308,
    description: "North-Western Bay • Accessible and forgiving Breva freeride spot with smooth rolling conditions.",
    sweetSpotSummary: "Optimal in 14–22 kt S/SSW Breva with gentle rolling chop.",
    idealDirections: ["S", "SSW", "SW"],
    idealDirectionDegrees: [170, 240],
    minPlaningWind: 11,
    idealWindMin: 14,
    idealWindMax: 22,
    comfortCeilingWind: 26,
    defaultStyle: "FLAT",
    directionScores: {
      S: 100,
      SSW: 90,
      SW: 85,
      default: 20,
    },
    styleRules: {
      bumpAndJumpThresholdWind: 20,
      favoredDirections: ["S", "SSW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 10, score: 20 },
      { wind: 14, score: 65 },
      { wind: 18, score: 95 },
      { wind: 22, score: 100 },
      { wind: 26, score: 70 },
      { wind: 32, score: 25 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.05,
      minFactor: 0.90,
      maxFactor: 1.25,
      directionModifiers: {
        S: 0.05,
        SSW: 0.04,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: { S: 18, SSW: 20, SW: 10, N: 6 },
      flatThresholdKt: 13,
      chopThresholdKt: 18,
      rampThresholdKt: 25,
      extremeThresholdKt: 35,
    },
    hardGates: [
      {
        id: "gravedona-convective-hazard",
        description: "Active convective hazard",
        regimes: ["COMO_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Severe convective downburst conditions.",
      },
    ],
  },
];
