import { RegionSpotConfig } from "@/types/region";

/**
 * Maremma Edition MVP Spot Configurations
 * Note: Coefficients and quality curves are initial provisional expert calibrations (BETA).
 */
export const MaremmaSpots: RegionSpotConfig[] = [
  {
    id: "talamone",
    name: "Talamone",
    latitude: 42.555,
    longitude: 11.132,
    description: "Bay of Talamone • Thermal acceleration sweetspot with flat to bump & jump water.",
    sweetSpotSummary: "Optimal in 16–24 kt NW/W flow; strong thermal reinforcement in summer afternoons.",
    idealDirections: ["NW", "WNW", "W", "SW", "NNW"],
    idealDirectionDegrees: [225, 340],
    minPlaningWind: 11,
    idealWindMin: 16,
    idealWindMax: 24,
    comfortCeilingWind: 28,
    defaultStyle: "FLAT",
    directionScores: {
      NW: 100,
      WNW: 95,
      W: 85,
      SW: 80,
      NNW: 75,
      SSW: 70,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 26,
      bumpAndJumpThresholdWind: 20,
      favoredDirections: ["NW", "WNW", "W"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 10, score: 20 },
      { wind: 14, score: 60 },
      { wind: 18, score: 95 },
      { wind: 22, score: 100 },
      { wind: 25, score: 85 },
      { wind: 28, score: 60 },
      { wind: 35, score: 20 },
      { wind: 40, score: 0 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.90,
      maxFactor: 1.45,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.10,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 18,
        boostAmount: 0.15,
      },
      directionModifiers: {
        NW: 0.10,
        WNW: 0.05,
        W: 0.05,
        SW: 0.0,
      },
    },
    hardGates: [
      {
        id: "talamone-offshore-east",
        description: "Offshore wind from inland hills (ENE/E/ESE)",
        directionRange: [60, 120],
        eligibility: "UNSUITABLE",
        reason: "Strongly offshore wind from inland hills creates dangerous drift and severe gustiness.",
      },
    ],
  },
  {
    id: "punta-ala",
    name: "Punta Ala",
    latitude: 42.81,
    longitude: 10.745,
    description: "Cape Punta Ala • Exposed wave & bump & jump arena facing the open Tyrrhenian sea.",
    sweetSpotSummary: "Optimal in 18–30 kt NW/W/SW winds; delivers the cleanest wave ramps in the region.",
    idealDirections: ["NW", "WNW", "W", "SW", "SSW"],
    idealDirectionDegrees: [210, 330],
    minPlaningWind: 13,
    idealWindMin: 18,
    idealWindMax: 30,
    comfortCeilingWind: 35,
    defaultStyle: "WAVE",
    directionScores: {
      NW: 100,
      WNW: 95,
      W: 95,
      SW: 90,
      SSW: 80,
      NNW: 70,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 20,
      bumpAndJumpThresholdWind: 16,
      favoredDirections: ["NW", "WNW", "W", "SW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 12, score: 15 },
      { wind: 16, score: 50 },
      { wind: 20, score: 85 },
      { wind: 26, score: 100 },
      { wind: 32, score: 90 },
      { wind: 36, score: 75 },
      { wind: 42, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.05,
      minFactor: 0.90,
      maxFactor: 1.30,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.05,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 17,
        boostAmount: 0.08,
      },
      directionModifiers: {
        NW: 0.05,
        WNW: 0.05,
        W: 0.05,
        SW: 0.05,
      },
    },
    hardGates: [
      {
        id: "punta-ala-offshore-east",
        description: "Offshore wind off the cape (NE/E/SE)",
        directionRange: [45, 135],
        eligibility: "UNSUITABLE",
        reason: "Offshore wind from the pine forest blows into the open channel with unstable gusts and hazardous drift.",
      },
    ],
  },
  {
    id: "marina-di-grosseto",
    name: "Marina di Grosseto",
    latitude: 42.718,
    longitude: 10.985,
    description: "Central Maremma Coast • Wide sandy beach with side-onshore breeze and bump & jump.",
    sweetSpotSummary: "Optimal in 16–26 kt NW/W/SW flows with consistent thermal assistance.",
    idealDirections: ["NW", "WNW", "W", "SW", "SSW"],
    idealDirectionDegrees: [210, 320],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 30,
    defaultStyle: "BUMP_AND_JUMP",
    directionScores: {
      NW: 95,
      WNW: 90,
      W: 90,
      SW: 90,
      SSW: 85,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["SW", "W", "NW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 15, score: 55 },
      { wind: 20, score: 95 },
      { wind: 24, score: 100 },
      { wind: 28, score: 80 },
      { wind: 34, score: 50 },
      { wind: 40, score: 20 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.05,
      minFactor: 0.90,
      maxFactor: 1.35,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.08,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 17,
        boostAmount: 0.10,
      },
      directionModifiers: {
        NW: 0.05,
        WNW: 0.05,
        W: 0.05,
        SW: 0.05,
      },
    },
    hardGates: [
      {
        id: "marina-grosseto-offshore",
        description: "Direct offshore wind from the mainland (NE/E/SE)",
        directionRange: [45, 135],
        eligibility: "UNSUITABLE",
        reason: "Direct offshore wind from the mainland creates unsafe drift and gusty offshore conditions.",
      },
    ],
  },
  {
    id: "giannella",
    name: "Giannella",
    latitude: 42.455,
    longitude: 11.185,
    description: "Tombolo della Giannella • Protected tombolo bay with flat water and gentle chop.",
    sweetSpotSummary: "Ideal in 16–25 kt NW/N flows; excellent flat-water comfort when open coast is rough.",
    idealDirections: ["NW", "NNW", "N", "WNW", "W"],
    idealDirectionDegrees: [280, 360],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 25,
    comfortCeilingWind: 30,
    defaultStyle: "FLAT",
    directionScores: {
      NW: 95,
      NNW: 90,
      N: 85,
      WNW: 80,
      W: 70,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 30,
      bumpAndJumpThresholdWind: 22,
      favoredDirections: ["NW", "NNW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 15, score: 50 },
      { wind: 20, score: 95 },
      { wind: 23, score: 100 },
      { wind: 27, score: 80 },
      { wind: 32, score: 50 },
      { wind: 40, score: 10 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.00,
      minFactor: 0.85,
      maxFactor: 1.25,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.05,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 17,
        boostAmount: 0.08,
      },
      directionModifiers: {
        NW: 0.05,
        NNW: 0.05,
        N: 0.0,
      },
    },
    hardGates: [
      {
        id: "giannella-offshore-south",
        description: "Offshore flow away from tombolo (SE/S/SSW)",
        directionRange: [135, 210],
        eligibility: "UNSUITABLE",
        reason: "Offshore flow creates hazardous drift away from the tombolo.",
      },
    ],
  },
  {
    id: "castiglione-della-pescaia",
    name: "Castiglione della Pescaia",
    latitude: 42.763,
    longitude: 10.88,
    description: "Northern Maremma Coast • Open bay with dynamic bump & jump and rolling swell.",
    sweetSpotSummary: "Optimal in 16–26 kt NW/W/SW flows with clean side-shore angle.",
    idealDirections: ["NW", "WNW", "W", "SW"],
    idealDirectionDegrees: [225, 325],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 30,
    defaultStyle: "BUMP_AND_JUMP",
    directionScores: {
      NW: 100,
      WNW: 90,
      W: 85,
      SW: 80,
      default: 30,
    },
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["NW", "W", "SW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 15 },
      { wind: 15, score: 55 },
      { wind: 20, score: 95 },
      { wind: 24, score: 100 },
      { wind: 28, score: 80 },
      { wind: 34, score: 50 },
      { wind: 40, score: 20 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.05,
      minFactor: 0.90,
      maxFactor: 1.30,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.08,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 17,
        boostAmount: 0.10,
      },
      directionModifiers: {
        NW: 0.08,
        WNW: 0.05,
        W: 0.05,
      },
    },
    hardGates: [
      {
        id: "castiglione-offshore-east",
        description: "Offshore wind from behind the hills (NE/E)",
        directionRange: [45, 120],
        eligibility: "UNSUITABLE",
        reason: "Offshore wind blowing from behind the hills creates dangerous offshore drift.",
      },
    ],
  },
];
