import { RegionSpotConfig } from "@/types/region";

export const GardaLakeSpots: RegionSpotConfig[] = [
  {
    id: "pra-de-la-fam",
    name: "Prà de la Fam",
    latitude: 45.740,
    longitude: 10.690,
    description: "Tignale, Western Shore • Legendary Pelèr Arena & Ramps",
    sweetSpotSummary: "Dawn to mid-morning Pelèr (N/NNE 18–28 kt) with steep ramps once morning sun illuminates the cliffs.",
    idealDirections: ["N", "NNE", "NNW"],
    idealDirectionDegrees: [340, 30],
    minPlaningWind: 14,
    idealWindMin: 18,
    idealWindMax: 30,
    comfortCeilingWind: 34,
    defaultStyle: "BUMP_AND_JUMP",
    preferredStyles: {
      BUMP_AND_JUMP: 1.0,
      CHOP: 0.9,
      FLAT: 0.4,
    },
    directionScores: {
      N: 100,
      NNE: 100,
      NNW: 90,
      NE: 80,
      default: 20,
    },
    styleRules: {
      waveThresholdWind: 26,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["N", "NNE", "NNW"],
    },
    regimeQualityCurves: {
      GARDA_PELER: [
        { wind: 0, score: 0 },
        { wind: 13, score: 35 },
        { wind: 17, score: 82 },
        { wind: 22, score: 98 },
        { wind: 28, score: 100 },
        { wind: 33, score: 85 },
        { wind: 38, score: 40 },
      ],
      GARDA_STRONG_NORTH: [
        { wind: 0, score: 0 },
        { wind: 15, score: 30 },
        { wind: 20, score: 75 },
        { wind: 26, score: 95 },
        { wind: 32, score: 90 },
        { wind: 38, score: 70 },
        { wind: 44, score: 30 },
      ],
      GARDA_FOEHN: [
        { wind: 0, score: 0 },
        { wind: 16, score: 30 },
        { wind: 22, score: 75 },
        { wind: 28, score: 92 },
        { wind: 35, score: 75 },
        { wind: 42, score: 40 },
      ],
      GARDA_ORA: [
        { wind: 0, score: 0 },
        { wind: 12, score: 20 },
        { wind: 16, score: 50 },
        { wind: 20, score: 65 },
        { wind: 25, score: 60 },
      ],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 13, score: 30 },
      { wind: 17, score: 75 },
      { wind: 22, score: 98 },
      { wind: 28, score: 100 },
      { wind: 33, score: 85 },
      { wind: 38, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.15,
      minFactor: 0.90,
      maxFactor: 1.45,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        maxBoost: 0.30,
        timeProfile: [
          { hour: 5, factor: 0.20 },
          { hour: 6, factor: 0.40 },
          { hour: 7, factor: 0.75 },
          { hour: 8, factor: 1.00 },
          { hour: 9, factor: 1.00 },
          { hour: 10, factor: 1.00 },
          { hour: 11, factor: 0.65 },
          { hour: 12, factor: 0.10 },
        ],
        directionFactors: {
          N: 1.0,
          NNE: 1.0,
          NNW: 0.9,
          NE: 0.7,
        },
        defaultDirectionFactor: 0.0,
        cloudCoverCurve: [
          { cloud: 0, factor: 1.0 },
          { cloud: 40, factor: 0.9 },
          { cloud: 80, factor: 0.6 },
          { cloud: 100, factor: 0.3 },
        ],
        synopticWindCurve: [
          { wind: 6, factor: 0.5 },
          { wind: 12, factor: 1.0 },
          { wind: 20, factor: 0.8 },
          { wind: 30, factor: 0.3 },
        ],
      },
      directionModifiers: {
        N: 0.15,
        NNE: 0.15,
        NNW: 0.05,
        S: -0.15,
        SSW: -0.20,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        N: 18,
        NNE: 16,
        NNW: 12,
        NE: 10,
        S: 25,
        SSW: 20,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 15,
      rampThresholdKt: 22,
      extremeThresholdKt: 35,
    },
    operatingWindow: {
      mode: "SOLAR_WITH_TWILIGHT",
      preSunriseMinutes: 30,
      earliestLocalTime: "05:00",
      latestLocalTime: "12:00",
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda: sudden violent gusts and lightning risk.",
      },
      {
        id: "southerly_shadow_peler",
        description: "Southerly wind shadow during morning hours",
        directionRange: [140, 220],
        maxWind: 14,
        eligibility: "UNSUITABLE",
        reason: "Weak southerly wind creates dead air and wind shadow under Tignale cliffs.",
      },
    ],
  },
  {
    id: "malcesine-navene",
    name: "Malcesine–Navene",
    latitude: 45.780,
    longitude: 10.820,
    description: "Eastern Shore • Early Morning Pelèr & Mountain Backdrop",
    sweetSpotSummary: "First-light Pelèr (N/NNE 16–26 kt) arriving very early, peaking around sunrise before weakening.",
    idealDirections: ["N", "NNE", "NNW"],
    idealDirectionDegrees: [340, 30],
    minPlaningWind: 13,
    idealWindMin: 18,
    idealWindMax: 28,
    comfortCeilingWind: 33,
    defaultStyle: "BUMP_AND_JUMP",
    preferredStyles: {
      BUMP_AND_JUMP: 1.0,
      CHOP: 0.9,
      FLAT: 0.5,
    },
    directionScores: {
      N: 100,
      NNE: 100,
      NNW: 90,
      NE: 80,
      S: 60,
      SSW: 65,
      default: 20,
    },
    styleRules: {
      waveThresholdWind: 25,
      bumpAndJumpThresholdWind: 17,
      favoredDirections: ["N", "NNE", "NNW"],
    },
    regimeQualityCurves: {
      GARDA_PELER: [
        { wind: 0, score: 0 },
        { wind: 12, score: 30 },
        { wind: 16, score: 75 },
        { wind: 21, score: 98 },
        { wind: 26, score: 100 },
        { wind: 31, score: 85 },
        { wind: 36, score: 40 },
      ],
      GARDA_STRONG_NORTH: [
        { wind: 0, score: 0 },
        { wind: 14, score: 30 },
        { wind: 19, score: 75 },
        { wind: 25, score: 95 },
        { wind: 32, score: 88 },
        { wind: 38, score: 65 },
        { wind: 44, score: 25 },
      ],
      GARDA_ORA: [
        { wind: 0, score: 0 },
        { wind: 11, score: 20 },
        { wind: 15, score: 60 },
        { wind: 18, score: 80 },
        { wind: 24, score: 75 },
      ],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 12, score: 30 },
      { wind: 16, score: 75 },
      { wind: 21, score: 98 },
      { wind: 26, score: 100 },
      { wind: 31, score: 85 },
      { wind: 36, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.12,
      minFactor: 0.90,
      maxFactor: 1.40,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        maxBoost: 0.28,
        timeProfile: [
          { hour: 4, factor: 0.30 },
          { hour: 5, factor: 0.70 },
          { hour: 6, factor: 1.00 },
          { hour: 7, factor: 1.00 },
          { hour: 8, factor: 1.00 },
          { hour: 9, factor: 0.80 },
          { hour: 10, factor: 0.40 },
          { hour: 11, factor: 0.00 },
        ],
        directionFactors: {
          N: 1.0,
          NNE: 1.0,
          NNW: 0.9,
          NE: 0.7,
        },
        defaultDirectionFactor: 0.0,
        cloudCoverCurve: [
          { cloud: 0, factor: 1.0 },
          { cloud: 40, factor: 0.9 },
          { cloud: 80, factor: 0.6 },
          { cloud: 100, factor: 0.3 },
        ],
        synopticWindCurve: [
          { wind: 6, factor: 0.5 },
          { wind: 12, factor: 1.0 },
          { wind: 20, factor: 0.8 },
          { wind: 30, factor: 0.3 },
        ],
      },
      directionModifiers: {
        N: 0.12,
        NNE: 0.12,
        NNW: 0.05,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        N: 12,
        NNE: 10,
        NNW: 14,
        S: 30,
        SSW: 26,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 14,
      rampThresholdKt: 20,
      extremeThresholdKt: 34,
    },
    operatingWindow: {
      mode: "SOLAR_WITH_TWILIGHT",
      preSunriseMinutes: 30,
      earliestLocalTime: "04:30",
      latestLocalTime: "11:30",
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda: sudden violent gusts and lightning risk.",
      },
    ],
  },
  {
    id: "torbole",
    name: "Torbole",
    latitude: 45.870,
    longitude: 10.875,
    description: "Northern Funnel • Iconic Afternoon Ora Capital",
    sweetSpotSummary: "Afternoon Ora (S/SSW 16–25 kt) funneling between steep northern cliffs with classic lake chop.",
    idealDirections: ["S", "SSW", "SSE"],
    idealDirectionDegrees: [160, 220],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 25,
    comfortCeilingWind: 30,
    defaultStyle: "CHOP",
    preferredStyles: {
      CHOP: 1.0,
      BUMP_AND_JUMP: 0.95,
      FLAT: 0.7,
    },
    directionScores: {
      S: 100,
      SSW: 100,
      SSE: 95,
      SW: 80,
      N: 50,
      NNE: 45,
      default: 20,
    },
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 16,
      favoredDirections: ["S", "SSW", "SSE"],
    },
    regimeQualityCurves: {
      GARDA_ORA: [
        { wind: 0, score: 0 },
        { wind: 11, score: 25 },
        { wind: 15, score: 75 },
        { wind: 19, score: 98 },
        { wind: 24, score: 100 },
        { wind: 28, score: 85 },
        { wind: 33, score: 40 },
      ],
      GARDA_PELER: [
        { wind: 0, score: 0 },
        { wind: 13, score: 30 },
        { wind: 17, score: 65 },
        { wind: 22, score: 75 },
        { wind: 28, score: 60 },
      ],
      GARDA_STRONG_NORTH: [
        { wind: 0, score: 0 },
        { wind: 15, score: 30 },
        { wind: 22, score: 70 },
        { wind: 28, score: 80 },
        { wind: 35, score: 60 },
      ],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 25 },
      { wind: 15, score: 75 },
      { wind: 19, score: 98 },
      { wind: 24, score: 100 },
      { wind: 28, score: 85 },
      { wind: 33, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.20,
      minFactor: 0.90,
      maxFactor: 1.50,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        maxBoost: 0.35,
        timeProfile: [
          { hour: 11, factor: 0.10 },
          { hour: 12, factor: 0.35 },
          { hour: 13, factor: 0.70 },
          { hour: 14, factor: 0.95 },
          { hour: 15, factor: 1.00 },
          { hour: 16, factor: 1.00 },
          { hour: 17, factor: 0.85 },
          { hour: 18, factor: 0.55 },
          { hour: 19, factor: 0.20 },
          { hour: 20, factor: 0.00 },
        ],
        directionFactors: {
          S: 1.0,
          SSW: 1.0,
          SSE: 0.9,
          SW: 0.7,
        },
        defaultDirectionFactor: 0.0,
        cloudCoverCurve: [
          { cloud: 0, factor: 1.0 },
          { cloud: 30, factor: 0.95 },
          { cloud: 70, factor: 0.5 },
          { cloud: 100, factor: 0.2 },
        ],
        synopticWindCurve: [
          { wind: 4, factor: 0.6 },
          { wind: 10, factor: 1.0 },
          { wind: 18, factor: 0.8 },
          { wind: 26, factor: 0.3 },
        ],
      },
      directionModifiers: {
        S: 0.20,
        SSW: 0.18,
        SSE: 0.15,
        N: -0.10,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        S: 40,
        SSW: 35,
        SSE: 38,
        SW: 25,
        N: 4,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 14,
      rampThresholdKt: 20,
      extremeThresholdKt: 32,
    },
    operatingWindow: {
      mode: "SOLAR",
      earliestLocalTime: "11:00",
      latestLocalTime: "20:00",
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda: sudden violent gusts and lightning risk.",
      },
    ],
  },
  {
    id: "riva-del-garda",
    name: "Riva del Garda",
    latitude: 45.885,
    longitude: 10.840,
    description: "Northwestern Shore • Ora Funnel & Monte Brione Flank",
    sweetSpotSummary: "Afternoon Ora breeze (S/SSW 15–24 kt) offering scenic flat-to-chop conditions near Monte Brione.",
    idealDirections: ["S", "SSW", "SSE"],
    idealDirectionDegrees: [160, 220],
    minPlaningWind: 12,
    idealWindMin: 15,
    idealWindMax: 24,
    comfortCeilingWind: 29,
    defaultStyle: "CHOP",
    preferredStyles: {
      CHOP: 1.0,
      BUMP_AND_JUMP: 0.85,
      FLAT: 0.8,
    },
    directionScores: {
      S: 100,
      SSW: 100,
      SSE: 90,
      SW: 75,
      default: 20,
    },
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 16,
      favoredDirections: ["S", "SSW", "SSE"],
    },
    regimeQualityCurves: {
      GARDA_ORA: [
        { wind: 0, score: 0 },
        { wind: 11, score: 25 },
        { wind: 14, score: 70 },
        { wind: 18, score: 98 },
        { wind: 23, score: 100 },
        { wind: 27, score: 80 },
        { wind: 32, score: 35 },
      ],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 25 },
      { wind: 14, score: 70 },
      { wind: 18, score: 98 },
      { wind: 23, score: 100 },
      { wind: 27, score: 80 },
      { wind: 32, score: 35 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.15,
      minFactor: 0.90,
      maxFactor: 1.42,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        maxBoost: 0.30,
        timeProfile: [
          { hour: 11, factor: 0.10 },
          { hour: 12, factor: 0.30 },
          { hour: 13, factor: 0.65 },
          { hour: 14, factor: 0.90 },
          { hour: 15, factor: 1.00 },
          { hour: 16, factor: 0.95 },
          { hour: 17, factor: 0.80 },
          { hour: 18, factor: 0.50 },
          { hour: 19, factor: 0.15 },
          { hour: 20, factor: 0.00 },
        ],
        directionFactors: {
          S: 1.0,
          SSW: 1.0,
          SSE: 0.85,
        },
        defaultDirectionFactor: 0.0,
        cloudCoverCurve: [
          { cloud: 0, factor: 1.0 },
          { cloud: 30, factor: 0.95 },
          { cloud: 70, factor: 0.5 },
          { cloud: 100, factor: 0.2 },
        ],
      },
      directionModifiers: {
        S: 0.15,
        SSW: 0.15,
        SSE: 0.10,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        S: 38,
        SSW: 32,
        SSE: 35,
        N: 3,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 14,
      rampThresholdKt: 20,
      extremeThresholdKt: 30,
    },
    operatingWindow: {
      mode: "SOLAR",
      earliestLocalTime: "11:00",
      latestLocalTime: "20:00",
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda: sudden violent gusts and lightning risk.",
      },
    ],
  },
  {
    id: "campione-garda",
    name: "Campione del Garda",
    latitude: 45.755,
    longitude: 10.750,
    description: "Western Cliffs • Dual Pelèr & Ora High-Wind Stadium",
    sweetSpotSummary: "Powerful morning Pelèr (N 18–28 kt) and accelerated afternoon Ora (S 16–24 kt) directly under towering cliffs.",
    idealDirections: ["N", "NNE", "NNW", "S", "SSW"],
    idealDirectionDegrees: [340, 210],
    minPlaningWind: 14,
    idealWindMin: 18,
    idealWindMax: 28,
    comfortCeilingWind: 34,
    defaultStyle: "BUMP_AND_JUMP",
    preferredStyles: {
      BUMP_AND_JUMP: 1.0,
      CHOP: 0.95,
      FLAT: 0.5,
    },
    directionScores: {
      N: 100,
      NNE: 95,
      NNW: 90,
      S: 95,
      SSW: 95,
      default: 20,
    },
    styleRules: {
      waveThresholdWind: 25,
      bumpAndJumpThresholdWind: 17,
      favoredDirections: ["N", "NNE", "S", "SSW"],
    },
    regimeQualityCurves: {
      GARDA_PELER: [
        { wind: 0, score: 0 },
        { wind: 13, score: 30 },
        { wind: 17, score: 75 },
        { wind: 22, score: 98 },
        { wind: 27, score: 100 },
        { wind: 32, score: 85 },
        { wind: 37, score: 40 },
      ],
      GARDA_ORA: [
        { wind: 0, score: 0 },
        { wind: 12, score: 25 },
        { wind: 16, score: 75 },
        { wind: 20, score: 98 },
        { wind: 25, score: 100 },
        { wind: 30, score: 80 },
        { wind: 35, score: 35 },
      ],
      GARDA_STRONG_NORTH: [
        { wind: 0, score: 0 },
        { wind: 15, score: 30 },
        { wind: 21, score: 75 },
        { wind: 27, score: 95 },
        { wind: 34, score: 85 },
        { wind: 40, score: 50 },
      ],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 13, score: 30 },
      { wind: 17, score: 75 },
      { wind: 22, score: 98 },
      { wind: 27, score: 100 },
      { wind: 32, score: 85 },
      { wind: 37, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.90,
      maxFactor: 1.38,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        maxBoost: 0.22,
        timeProfile: [
          { hour: 5, factor: 0.20 },
          { hour: 6, factor: 0.40 },
          { hour: 7, factor: 0.65 },
          { hour: 8, factor: 0.75 },
          { hour: 9, factor: 0.70 },
          { hour: 10, factor: 0.40 },
          { hour: 13, factor: 0.50 },
          { hour: 14, factor: 0.85 },
          { hour: 15, factor: 1.00 },
          { hour: 16, factor: 0.95 },
          { hour: 17, factor: 0.70 },
          { hour: 18, factor: 0.30 },
        ],
        directionFactors: {
          N: 1.0,
          NNE: 0.95,
          S: 0.95,
          SSW: 0.95,
        },
        defaultDirectionFactor: 0.0,
      },
      directionModifiers: {
        N: 0.15,
        NNE: 0.12,
        S: 0.15,
        SSW: 0.15,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        N: 16,
        NNE: 14,
        S: 28,
        SSW: 24,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 15,
      rampThresholdKt: 21,
      extremeThresholdKt: 34,
    },
    operatingWindow: {
      mode: "SOLAR_WITH_TWILIGHT",
      preSunriseMinutes: 30,
      earliestLocalTime: "05:00",
      latestLocalTime: "20:00",
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda: sudden violent gusts and lightning risk.",
      },
    ],
  },
  {
    id: "limone",
    name: "Limone sul Garda",
    latitude: 45.815,
    longitude: 10.790,
    description: "Northwestern Shore • Steep Cliffs & Dual Regime Flow",
    sweetSpotSummary: "Early Pelèr from the north and afternoon Ora acceleration near the northern funnel entryway.",
    idealDirections: ["N", "NNE", "S", "SSW"],
    idealDirectionDegrees: [340, 210],
    minPlaningWind: 13,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 32,
    defaultStyle: "CHOP",
    preferredStyles: {
      CHOP: 1.0,
      BUMP_AND_JUMP: 0.9,
      FLAT: 0.6,
    },
    directionScores: {
      N: 95,
      NNE: 95,
      S: 95,
      SSW: 95,
      default: 25,
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 12, score: 25 },
      { wind: 16, score: 75 },
      { wind: 20, score: 98 },
      { wind: 25, score: 100 },
      { wind: 30, score: 85 },
      { wind: 35, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.12,
      minFactor: 0.90,
      maxFactor: 1.38,
      directionModifiers: {
        N: 0.10,
        S: 0.12,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        N: 10,
        S: 32,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 14,
      extremeThresholdKt: 32,
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda.",
      },
    ],
  },
  {
    id: "gargnano",
    name: "Gargnano",
    latitude: 45.690,
    longitude: 10.660,
    description: "Western Central Shore • Wide Basin & Regular Ora Breeze",
    sweetSpotSummary: "Wide lake section offering smooth afternoon Ora and broad chop, great for freeride.",
    idealDirections: ["S", "SSW", "SSE"],
    idealDirectionDegrees: [160, 220],
    minPlaningWind: 12,
    idealWindMin: 15,
    idealWindMax: 24,
    comfortCeilingWind: 28,
    defaultStyle: "CHOP",
    directionScores: {
      S: 100,
      SSW: 95,
      SSE: 95,
      default: 20,
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 25 },
      { wind: 15, score: 75 },
      { wind: 18, score: 98 },
      { wind: 23, score: 100 },
      { wind: 28, score: 80 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.08,
      minFactor: 0.90,
      maxFactor: 1.30,
      directionModifiers: {
        S: 0.08,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        S: 20,
        N: 22,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 14,
      extremeThresholdKt: 30,
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda.",
      },
    ],
  },
  {
    id: "brenzone",
    name: "Brenzone",
    latitude: 45.700,
    longitude: 10.770,
    description: "Eastern Central Shore • Broad Lake Chop & Thermal Transition",
    sweetSpotSummary: "Good morning Pelèr extension and afternoon Ora with wide open water and steady chop.",
    idealDirections: ["N", "NNE", "S", "SSW"],
    idealDirectionDegrees: [340, 220],
    minPlaningWind: 13,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 30,
    defaultStyle: "CHOP",
    directionScores: {
      N: 95,
      NNE: 95,
      S: 95,
      SSW: 95,
      default: 20,
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 12, score: 25 },
      { wind: 16, score: 75 },
      { wind: 20, score: 98 },
      { wind: 25, score: 100 },
      { wind: 30, score: 80 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.90,
      maxFactor: 1.35,
      directionModifiers: {
        N: 0.10,
        S: 0.10,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        N: 20,
        S: 22,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 14,
      extremeThresholdKt: 30,
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda.",
      },
    ],
  },
  {
    id: "torri-del-benaco",
    name: "Torri del Benaco",
    latitude: 45.610,
    longitude: 10.685,
    description: "Southeastern Shore • Open Water & Gentle Southerly Ora",
    sweetSpotSummary: "Southern lake entrance for afternoon Ora breeze over wide, forgiving waters.",
    idealDirections: ["S", "SSW", "SW"],
    idealDirectionDegrees: [160, 230],
    minPlaningWind: 12,
    idealWindMin: 15,
    idealWindMax: 22,
    comfortCeilingWind: 26,
    defaultStyle: "CHOP",
    directionScores: {
      S: 100,
      SSW: 95,
      SW: 90,
      default: 20,
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 11, score: 25 },
      { wind: 14, score: 75 },
      { wind: 18, score: 100 },
      { wind: 23, score: 90 },
      { wind: 28, score: 60 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.05,
      minFactor: 0.90,
      maxFactor: 1.25,
      directionModifiers: {
        S: 0.05,
      },
    },
    lakeProfile: {
      fetchByDirectionKm: {
        S: 15,
        N: 30,
      },
      flatThresholdKt: 10,
      chopThresholdKt: 14,
      extremeThresholdKt: 28,
    },
    hardGates: [
      {
        id: "convective_hazard",
        description: "Severe convective squall or storm risk",
        regimes: ["GARDA_CONVECTIVE_HAZARD"],
        eligibility: "UNSUITABLE",
        reason: "Convective storm hazard on Lake Garda.",
      },
    ],
  },
];
