import { RegionSpotConfig } from "@/types/region";
import { KOUREMENOS_PROFILE, TENDA_PROFILE, XEROKAMPOS_PROFILE } from "@/config/windProfiles";

export const EasternCreteSpots: RegionSpotConfig[] = [
  {
    id: "kouremenos",
    name: "Kouremenos",
    latitude: 35.201,
    longitude: 26.273,
    description: "Palekastro Bay • Thermal sweetspot with side-shore Meltemi and flat/chop water.",
    sweetSpotSummary: "Optimal at 18–24 kt NW Meltemi; penalizes excessive gusts (>30 kt).",
    idealDirections: ["NW", "NNW", "WNW", "N", "W"],
    idealDirectionDegrees: [290, 340],
    minPlaningWind: 11,
    idealWindMin: 18,
    idealWindMax: 24,
    comfortCeilingWind: 26,
    defaultStyle: "FLAT",
    directionScores: KOUREMENOS_PROFILE.directionScores,
    styleRules: {
      waveThresholdWind: 26,
      bumpAndJumpThresholdWind: 22,
      favoredDirections: ["NW", "NNW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 10, score: 10 },
      { wind: 14, score: 40 },
      { wind: 18, score: 90 },
      { wind: 22, score: 100 },
      { wind: 24, score: 95 },
      { wind: 26, score: 75 },
      { wind: 28, score: 55 },
      { wind: 32, score: 20 },
      { wind: 40, score: 0 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.15,
      minFactor: 0.90,
      maxFactor: 1.45,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.10,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 18,
        boostAmount: 0.15,
      },
      directionModifiers: {
        NW: 0.10,
        NNW: 0.05,
        WNW: 0.05,
        N: 0.0,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "NW", factor: 0.45 },
        { direction: "NNW", factor: 0.45 },
        { direction: "N", factor: 0.50 },
        { direction: "WNW", factor: 0.40 },
      ],
      preferredWaveHeight: {
        min: 0.2,
        idealMin: 0.3,
        idealMax: 0.8,
        max: 1.4,
      },
      preferredStates: {
        FLAT: 1.0,
        CHOP: 0.85,
        BUMP_AND_JUMP: 0.5,
        WAVE: 0.2,
      },
    },
  },
  {
    id: "tenda",
    name: "Tenda",
    latitude: 35.318,
    longitude: 26.312,
    description: "Cape Sidero • Exposed wild northern tip receiving direct Meltemi swell and wave ramps.",
    sweetSpotSummary: "Thrives in strong Meltemi (22–34 kt); provides powerful jumping ramps.",
    idealDirections: ["NW", "NNW", "N", "WNW", "NNE", "NE"],
    idealDirectionDegrees: [315, 30],
    minPlaningWind: 14,
    idealWindMin: 22,
    idealWindMax: 34,
    comfortCeilingWind: 36,
    defaultStyle: "WAVE",
    directionScores: TENDA_PROFILE.directionScores,
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["NNW", "N", "NNE", "NW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 12, score: 10 },
      { wind: 16, score: 45 },
      { wind: 20, score: 75 },
      { wind: 25, score: 95 },
      { wind: 30, score: 100 },
      { wind: 35, score: 90 },
      { wind: 40, score: 65 },
      { wind: 45, score: 30 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.15,
      minFactor: 0.90,
      maxFactor: 1.25,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.05,
      diurnalThermalBoost: {
        startHour: 12,
        endHour: 19,
        boostAmount: 0.05,
      },
      directionModifiers: {
        NW: 0.05,
        NNW: 0.05,
        N: 0.0,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "N", factor: 1.00 },
        { direction: "NNW", factor: 1.00 },
        { direction: "NNE", factor: 0.95 },
        { direction: "NW", factor: 0.90 },
        { direction: "NE", factor: 0.85 },
      ],
      preferredWaveHeight: {
        min: 0.8,
        idealMin: 1.4,
        idealMax: 2.8,
        max: 4.0,
      },
      preferredPeriod: {
        min: 5.5,
        idealMin: 7.0,
        idealMax: 10.5,
      },
      preferredWaveDirections: ["N", "NNW", "NNE", "NW"],
      preferredStates: {
        WAVE: 1.0,
        BUMP_AND_JUMP: 0.8,
        CHOP: 0.3,
        FLAT: 0.1,
      },
    },
  },
  {
    id: "xerokampos",
    name: "Xerokampos",
    latitude: 35.035,
    longitude: 26.218,
    description: "South-East Crete • Prime alternative spot receiving clean side-onshore thermal breeze under W/SW flow.",
    sweetSpotSummary: "Ideal in non-Meltemi W/SW regimes (16–25 kt); strictly unsuitable during Meltemi (hazardous offshore).",
    idealDirections: ["WSW", "SW", "W", "SSW"],
    idealDirectionDegrees: [200, 270],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 32,
    defaultStyle: "BUMP_AND_JUMP",
    directionScores: XEROKAMPOS_PROFILE.directionScores,
    styleRules: {
      waveThresholdWind: 22,
      bumpAndJumpThresholdWind: 16,
      favoredDirections: ["WSW", "SW", "W"],
    },
    hardGates: [
      {
        id: "xerokampos-meltemi-exclusion",
        description: "Hazardous offshore flow during Meltemi",
        regimes: ["MELTEMI_STRONG", "MELTEMI_MODERATE", "MELTEMI_LIGHT"],
        eligibility: "UNSUITABLE",
        reason: "OFFSHORE_MELTEMI",
      },
    ],
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 10, score: 10 },
      { wind: 14, score: 50 },
      { wind: 18, score: 85 },
      { wind: 22, score: 100 },
      { wind: 26, score: 90 },
      { wind: 30, score: 70 },
      { wind: 35, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.90,
      maxFactor: 1.40,
      diurnalThermalBoost: {
        model: "DYNAMIC",
        enabled: true,
        correctionMode: "HYBRID",
        monthFactors: {
          4: 0.40,
          5: 0.85,
          6: 1.00,
          7: 1.00,
          8: 1.00,
          9: 0.85,
          10: 0.40,
        },
        timeProfile: [
          { hour: 10.0, factor: 0.10 },
          { hour: 11.0, factor: 0.35 },
          { hour: 12.0, factor: 0.65 },
          { hour: 13.0, factor: 0.85 },
          { hour: 14.0, factor: 1.00 },
          { hour: 15.0, factor: 1.00 },
          { hour: 16.0, factor: 0.95 },
          { hour: 17.0, factor: 0.80 },
          { hour: 18.0, factor: 0.50 },
          { hour: 19.0, factor: 0.20 },
          { hour: 20.0, factor: 0.00 },
        ],
        directionFactors: {
          WSW: 1.00,
          SW: 1.00,
          W: 0.90,
          SSW: 0.70,
        },
        defaultDirectionFactor: 0.0,
        synopticWindCurve: [
          { wind: 0, factor: 0.30 },
          { wind: 6, factor: 0.75 },
          { wind: 10, factor: 1.00 },
          { wind: 12, factor: 1.00 },
          { wind: 15, factor: 0.80 },
          { wind: 18, factor: 0.40 },
          { wind: 22, factor: 0.00 },
        ],
        cloudCoverCurve: [
          { cloud: 0, factor: 1.00 },
          { cloud: 20, factor: 0.95 },
          { cloud: 50, factor: 0.60 },
          { cloud: 80, factor: 0.20 },
          { cloud: 100, factor: 0.00 },
        ],
        minThermalStrength: 0.15,
        minimumConfidenceForCorrection: 0.45,
        maxAdditiveBoostKt: 12,
        maxMultiplicativeBoost: 0.05,
        maxThermalCorrectedWindKt: 27,
        buildRateLimitKtPerHour: 5,
        decayRateLimitKtPerHour: 6,
      },
      directionModifiers: {
        WSW: 0.05,
        SW: 0.0,
        W: 0.0,
      },
    },
    seaProfile: {
      exposureDirections: [
        { direction: "SW", factor: 0.90 },
        { direction: "WSW", factor: 0.90 },
        { direction: "W", factor: 0.80 },
        { direction: "SSW", factor: 0.85 },
        { direction: "S", factor: 0.70 },
      ],
      preferredWaveHeight: {
        min: 0.4,
        idealMin: 0.8,
        idealMax: 1.8,
        max: 2.6,
      },
      preferredStates: {
        BUMP_AND_JUMP: 1.0,
        WAVE: 0.75,
        FLAT: 0.6,
        CHOP: 0.5,
      },
    },
  },
];
