import { RegionSpotConfig } from "@/types/region";

export const EasternCreteSpots: RegionSpotConfig[] = [
  {
    id: "kouremenos",
    name: "Kouremenos",
    latitude: 35.201,
    longitude: 26.273,
    description: "Palekastro Bay • Thermal sweetspot with side-shore Meltemi and flat/chop water.",
    sweetSpotSummary: "Optimal at 18–24 kt NW Meltemi; penalizes excessive gusts (>30 kt).",
    idealDirections: ["NW", "NNW", "WNW"],
    idealDirectionDegrees: [290, 340],
    minPlaningWind: 11,
    idealWindMin: 18,
    idealWindMax: 24,
    comfortCeilingWind: 26,
    defaultStyle: "FLAT",
    styleRules: {
      waveThresholdWind: 26,
      bumpAndJumpThresholdWind: 22,
      favoredDirections: ["NW", "NNW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 10, score: 10 },
      { wind: 14, score: 40 },
      { wind: 18, score: 90 },
      { wind: 22, score: 100 },
      { wind: 24, score: 95 },
      { wind: 26, score: 75 },
      { wind: 28, score: 55 },
      { wind: 32, score: 20 },
      { wind: 40, score: 0 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.15,
      minFactor: 0.90,
      maxFactor: 1.45,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.10,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 18,
        boostAmount: 0.15,
      },
      directionModifiers: {
        NW: 0.05,
        NNW: 0.05,
        WNW: 0.0,
      },
    },
  },
  {
    id: "tenda",
    name: "Tenda",
    latitude: 35.318,
    longitude: 26.312,
    description: "Cape Sidero • Exposed wild northern tip receiving direct Meltemi swell and wave ramps.",
    sweetSpotSummary: "Thrives in strong Meltemi (22–34 kt); provides powerful jumping ramps.",
    idealDirections: ["NNW", "N", "NNE", "NW"],
    idealDirectionDegrees: [315, 30],
    minPlaningWind: 14,
    idealWindMin: 22,
    idealWindMax: 34,
    comfortCeilingWind: 36,
    defaultStyle: "WAVE",
    styleRules: {
      waveThresholdWind: 24,
      bumpAndJumpThresholdWind: 18,
      favoredDirections: ["NNW", "N", "NNE", "NW"],
    },
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 12, score: 10 },
      { wind: 16, score: 45 },
      { wind: 20, score: 75 },
      { wind: 25, score: 95 },
      { wind: 30, score: 100 },
      { wind: 35, score: 90 },
      { wind: 40, score: 65 },
      { wind: 45, score: 30 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.25,
      minFactor: 1.0,
      maxFactor: 1.55,
      summerBoostMonths: [6, 7, 8],
      summerBoostAmount: 0.05,
      diurnalThermalBoost: {
        startHour: 12,
        endHour: 19,
        boostAmount: 0.10,
      },
      directionModifiers: {
        NNW: 0.10,
        N: 0.10,
        NNE: 0.05,
      },
    },
  },
  {
    id: "xerokampos",
    name: "Xerokampos",
    latitude: 35.035,
    longitude: 26.218,
    description: "South-East Crete • Prime alternative spot receiving clean side-onshore thermal breeze under W/SW flow.",
    sweetSpotSummary: "Ideal in non-Meltemi W/SW regimes (16–25 kt); strictly unsuitable during Meltemi (hazardous offshore).",
    idealDirections: ["WSW", "SW", "SSW", "W", "S"],
    idealDirectionDegrees: [200, 270],
    minPlaningWind: 12,
    idealWindMin: 16,
    idealWindMax: 26,
    comfortCeilingWind: 32,
    defaultStyle: "BUMP_AND_JUMP",
    styleRules: {
      waveThresholdWind: 22,
      bumpAndJumpThresholdWind: 16,
      favoredDirections: ["WSW", "SW", "W"],
    },
    hardGates: [
      {
        id: "xerokampos-meltemi-exclusion",
        description: "Hazardous gusty offshore flow during Meltemi",
        regimes: ["MELTEMI_STRONG", "MELTEMI_MODERATE", "MELTEMI_LIGHT"],
        directionRange: [300, 360],
        eligibility: "UNSUITABLE",
        reason: "OFFSHORE_MELTEMI",
      },
    ],
    qualityCurve: [
      { wind: 0, score: 0 },
      { wind: 10, score: 10 },
      { wind: 14, score: 50 },
      { wind: 18, score: 85 },
      { wind: 22, score: 100 },
      { wind: 26, score: 90 },
      { wind: 30, score: 70 },
      { wind: 35, score: 40 },
    ],
    localCorrection: {
      baseCorrectionFactor: 1.10,
      minFactor: 0.85,
      maxFactor: 1.35,
      summerBoostMonths: [5, 6, 7, 8, 9],
      summerBoostAmount: 0.05,
      diurnalThermalBoost: {
        startHour: 13,
        endHour: 18,
        boostAmount: 0.15,
      },
      directionModifiers: {
        SW: 0.10,
        WSW: 0.10,
        W: 0.05,
      },
    },
  },
];
